import { LitElement, PropertyValues, TemplateResult } from 'lit';
import { SortParam } from '@internetarchive/search-service';
import { CollectionNameCacheInterface } from '@internetarchive/collection-name-cache';
import { TileModel } from '../../models';
import '../mediatype-icon';
import '../item-tile-image';
export declare class TileList extends LitElement {
    model?: TileModel;
    baseNavigationUrl?: string;
    collectionNameCache?: CollectionNameCacheInterface;
    currentWidth?: number;
    currentHeight?: number;
    sortParam: SortParam | null;
    mobileBreakpoint?: number;
    private collectionLinks;
    baseImageUrl?: string;
    protected updated(changed: PropertyValues): void;
    private fetchCollectionNames;
    render(): TemplateResult<1>;
    private get mobileTemplate();
    private get desktopTemplate();
    private get detailsTemplate();
    private get imgTemplate();
    private get iconRightTemplate();
    private get collectionColor();
    private get titleTemplate();
    private get itemLineTemplate();
    private get sourceTemplate();
    private get volumeTemplate();
    private get issueTemplate();
    private get creatorTemplate();
    private get datePublishedTemplate();
    private get dateSortByTemplate();
    private get viewsTemplate();
    private get ratingTemplate();
    private get reviewsTemplate();
    private get topicsTemplate();
    private get collectionsTemplate();
    private get descriptionTemplate();
    private metadataTemplate;
    private labelTemplate;
    private searchLink;
    private detailsLink;
    private get date();
    private get classSize();
    private get formatSize();
    static get styles(): import("lit").CSSResult;
}
