import { LitElement, PropertyValues } from 'lit';
import '../src/collection-browser';
export declare class AppRoot extends LitElement {
    private searchService;
    private resizeObserver;
    private localCache;
    private collectionNameCache;
    private currentPage?;
    private searchQuery?;
    private cellWidth;
    private cellHeight;
    private rowGap;
    private colGap;
    private baseQueryField;
    private pageNumberInput;
    private collectionBrowser;
    private searchPressed;
    private changePagePressed;
    protected updated(changed: PropertyValues): void;
    private queryUpdated;
    render(): import("lit-html").TemplateResult<1>;
    private baseQueryChanged;
    private outlineChanged;
    private rowGapChanged;
    private colGapChanged;
    private widthChanged;
    private heightChanged;
    private visiblePageChanged;
    static styles: import("lit").CSSResult;
}
