export const mediatypeColor: { [key: string]: string } = {
  account: '#000000',
  audio: '#8fdaef',
  data: '#333333',
  etree: '#3871c1',
  film: '#bf1b2c',
  image: '#62c4a9',
  movies: '#bf1b2c',
  software: '#80cc28',
  texts: '#f9a72b',
  tv: '#f25d54',
  video: '#bf1b2c',
  web: '#fddd10',
};

export const mediatypeText: { [key: string]: string } = {
  account: 'Account',
  audio: 'Audio',
  collection: 'Collection',
  data: 'Data',
  etree: 'E-tree',
  film: 'Film',
  image: 'Image',
  movies: 'Movie',
  radio: 'Radio',
  software: 'Software',
  texts: 'Text',
  tv: 'TV',
  video: 'Video',
  web: 'Web',
};
